export const products = [
    {
        id: 1,
        brand:"",
        name: 'Polera Blue Eyes Gojo de Jujutsu Kaisen',
        price: 86,
        image: './img/products/f9.webp',
        stars: 4,
    },
    {
        id: 2,
        brand:"sugoi",
        name: 'Polera Nave Capsule Corp de Dragon Ball',
        price: 100,
        image: './img/products/f13.webp',
        stars: 5,
    },
    {
        id: 3,
        brand:"adidas",
        name: 'Short Bandera Pirata Luffy de One Piece',
        price: 59,
        image: './img/products/f12.webp',
        stars: 4,
    },
    {
        id: 4,
        brand:"sugoi",
        name: 'Polo Over Acid Freedom de Shingeki No Kyojin',
        price: 70,
        image: './img/products/f10.webp',
        stars: 5,
    },
    {
        id: 5,
        brand:"adidas",
        name: 'Polera Nave Capsule Corp de Dragon Ball',
        price: 100,
        image: './img/products/f1.jpg',
        stars: 5,
    },
    {
        id: 6,
        brand:"adidas",
        name: 'Polera Blue Eyes Gojo de Jujutsu Kaisen',
        price: 86,
        image: './img/products/f2.jpg',
        stars: 4,
    },
    {
        id: 7,
        brand:"adidas",
        name: 'Polera Nave Capsule Corp de Dragon Ball',
        price: 100,
        image: './img/products/f3.jpg',
        stars: 5,
    },
    {
        id: 8,
        brand:"adidas",
        name: 'Short Bandera Pirata Luffy de One Piece',
        price: 59,
        image: './img/products/f4.jpg',
        stars: 4,
    },
    {
        id: 9,
        brand:"adidas",
        name: 'Polo Over Acid Freedom de Shingeki No Kyojin',
        price: 70,
        image: './img/products/f5.jpg',
        stars: 5,
    },
    {
        id: 10,
        brand:"adidas",
        name: 'Polera Nave Capsule Corp de Dragon Ball',
        price: 100,
        image: './img/products/f6.jpg',
        stars: 5,
    },
    {
        id: 11,
        brand:"adidas",
        name: 'Polera Blue Eyes Gojo de Jujutsu Kaisen',
        price: 86,
        image: './img/products/f7.jpg',
        stars: 4,
    },
    {
        id: 12,
        brand:"adidas",
        name: 'Polera Nave Capsule Corp de Dragon Ball',
        price: 100,
        image: './img/products/f8.jpg',
        stars: 5,
    },
]


